// packages/main-app/src/App.vue
<script setup lang="ts">
import { onMounted, provide } from 'vue'
import { registerMicroApps, start, initGlobalState } from 'qiankun'
import { microApps } from '@/config/apps'

const actions = initGlobalState({
  count: 0,
  user: {
    name: 'Guest',
    role: 'visitor'
  },
  theme: 'light'
})

actions.onGlobalStateChange((state, prev) => {
  console.log('Global state changed:', prev, '->', state)
})

provide('GlobalStateActions', actions)

onMounted(() => {
  registerMicroApps(microApps, {
    beforeLoad: (app) => {
      console.log('before load:', app.name)
      return Promise.resolve()
    },
    beforeMount: (app) => {
      console.log('before mount:', app.name)
      return Promise.resolve()
    },
    afterMount: (app) => {
      console.log('after mount:', app.name)
      return Promise.resolve()
    },
    beforeUnmount: (app) => {
      console.log('before unmount:', app.name)
      return Promise.resolve()
    },
    afterUnmount: (app) => {
      console.log('after unmount:', app.name)
      return Promise.resolve()
    }
  })

  start({
    sandbox: {
      strictStyleIsolation: true
    }
  })
})
</script>

<template>
  <div class="main-app">
    <nav class="nav-bar">
      <h1 class="logo">Qiankun 微前端教学项目</h1>
      <ul class="nav-links">
        <li><router-link to="/">首页</router-link></li>
        <li><router-link to="/react">React 微应用</router-link></li>
        <li><router-link to="/vue">Vue 微应用</router-link></li>
        <li><router-link to="/static">静态微应用</router-link></li>
      </ul>
    </nav>
    <main class="content">
      <router-view />
    </main>
  </div>
</template>

<style scoped>
.main-app {
  min-height: 100vh;
  background: #f5f5f5;
}

.nav-bar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 32px;
  background: #2c3e50;
  color: white;
}

.logo {
  font-size: 20px;
  font-weight: 600;
}

.nav-links {
  display: flex;
  gap: 24px;
  list-style: none;
}

.nav-links a {
  color: white;
  text-decoration: none;
  padding: 8px 16px;
  border-radius: 4px;
  transition: background 0.3s;
}

.nav-links a:hover,
.nav-links a.router-link-active {
  background: #34495e;
}

.content {
  padding: 24px;
}
</style>

// qiankun/packages/main-angular/src/app/app.component.ts
import { Component, OnInit, NgZone } from '@angular/core'
import { registerMicroApps, start, initGlobalState } from 'qiankun'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'Angular 主应用'
  currentPath = ''

  constructor(private ngZone: NgZone) {}

  ngOnInit(): void {
    this.ngZone.runOutsideAngular(() => {
      const microApps = [
        {
          name: 'react-app',
          entry: '//localhost:3000',
          container: '#micro-container',
          activeRule: '/react'
        },
        {
          name: 'vue-app',
          entry: '//localhost:8081',
          container: '#micro-container',
          activeRule: '/vue'
        },
        {
          name: 'static-app',
          entry: '//localhost:8082',
          container: '#micro-container',
          activeRule: '/static'
        }
      ]

      const actions = initGlobalState({
        count: 0,
        user: { name: 'Guest', role: 'visitor' },
        theme: 'light'
      })

      actions.onGlobalStateChange((state: Record<string, unknown>) => {
        console.log('Global state changed:', state)
      })

      registerMicroApps(microApps, {
        beforeLoad: (app) => {
          console.log('before load:', app.name)
          return Promise.resolve()
        },
        beforeMount: (app) => {
          console.log('before mount:', app.name)
          return Promise.resolve()
        },
        afterMount: (app) => {
          console.log('after mount:', app.name)
          return Promise.resolve()
        },
        beforeUnmount: (app) => {
          console.log('before unmount:', app.name)
          return Promise.resolve()
        },
        afterUnmount: (app) => {
          console.log('after unmount:', app.name)
          return Promise.resolve()
        }
      })

      start({
        sandbox: { strictStyleIsolation: true }
      })
    })
  }

  navigate(path: string): void {
    this.currentPath = path
  }
}
<div class="main-app">
  <nav class="nav-bar">
    <h1 class="logo">{{ title }}</h1>
    <ul class="nav-links">
      <li>
        <a routerLink="/" routerLinkActive="active" (click)="navigate('/')">首页</a>
      </li>
      <li>
        <a routerLink="/react" routerLinkActive="active" (click)="navigate('/react')">React 微应用</a>
      </li>
      <li>
        <a routerLink="/vue" routerLinkActive="active" (click)="navigate('/vue')">Vue 微应用</a>
      </li>
      <li>
        <a routerLink="/static" routerLinkActive="active" (click)="navigate('/static')">静态微应用</a>
      </li>
    </ul>
  </nav>
  <main class="content">
    <router-outlet></router-outlet>
  </main>
</div>
